services:
  # MySQL cho Auth Service (auth_db)
  mysql-auth:
    image: mysql:8.0
    container_name: mysql-auth
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1704
      MYSQL_DATABASE: auth_db
    ports:
      - "3307:3306" # Host port 3307 ánh xạ tới container port 3306
    volumes:
      - mysql-auth-data:/var/lib/mysql

  # MySQL cho Secret Code Service (secret_code_db)
  mysql-secret:
    image: mysql:8.0
    container_name: mysql-secret
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1704
      MYSQL_DATABASE: secret_code_db
    ports:
      - "3308:3306" # Host port 3308 ánh xạ tới container port 3306
    volumes:
      - mysql-secret-data:/var/lib/mysql

  # MySQL cho Product Service (product_db)
  mysql-product:
    image: mysql:8.0
    container_name: mysql-product
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1704
      MYSQL_DATABASE: product_db
    ports:
      - "3310:3306" # Host port 3309 ánh xạ tới container port 3306
    volumes:
      - mysql-product-data:/var/lib/mysql

  # ------------------------------------------------------------------------------------

  # Auth Service
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "3000:3000"
    env_file:
      - ./auth-service/.env
    depends_on:
      - mysql-auth

  # Secret Code Service
  secret-code-service:
    build:
      context: ./secret-code-service
      dockerfile: Dockerfile
    container_name: secret-code-service
    ports:
      - "3005:3005"
    env_file:
      - ./secret-code-service/.env
    depends_on:
      - mysql-secret

  # Product Service
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "3004:3004"
    volumes:
      - ./product-service/images:/home/app/images
    env_file:
      - ./product-service/.env
    depends_on:
      - mysql-product

volumes:
  mysql-auth-data:
  mysql-secret-data:
  mysql-product-data:
